export const relatedToolsMap: Record<string, string[]> = {
  "word-counter": [
    "character-counter",
    "line-counter",
    "keyword-extractor",
    "slug-generator",
    "remove-html-tags",
    "case-swapper",
  ],
  "character-counter": [
    "word-counter",
    "line-counter",
    "remove-html-tags",
    "slug-generator",
    "case-swapper",
    "keyword-extractor",
  ],
  "json-formatter": [
    "json-minifier",
    "json-validator",
    "json-to-csv",
    "csv-to-json",
    "json-to-yaml",
    "yaml-to-json",
  ],
  "json-minifier": [
    "json-formatter",
    "json-validator",
    "json-to-csv",
    "csv-to-json",
    "json-to-yaml",
    "yaml-to-json",
  ],
  "password-generator": [
    "password-strength-checker",
    "uuid-generator",
    "random-number-generator",
    "random-string-generator",
    "sha256-generator",
    "md5-generator",
  ],
  "password-strength-checker": [
    "password-generator",
    "sha256-generator",
    "md5-generator",
    "uuid-generator",
    "random-string-generator",
    "random-number-generator",
  ],
  "slug-generator": [
    "word-counter",
    "character-counter",
    "keyword-extractor",
    "meta-tag-generator",
    "utm-builder",
    "url-parser",
  ],
  "timestamp-converter": [
    "timestamp-now",
    "unix-time-to-date",
    "date-to-unix-time",
    "url-parser",
    "json-formatter",
    "query-string-parser",
  ],
  "url-parser": [
    "query-string-parser",
    "query-string-builder",
    "url-validator",
    "utm-builder",
    "redirect-checker",
    "http-status-checker",
  ],
  "sha256-generator": [
    "md5-generator",
    "sha1-generator",
    "password-generator",
    "password-strength-checker",
    "hash-compare",
    "bcrypt-generator",
  ],
  "meta-tag-generator": [
    "open-graph-generator",
    "twitter-card-generator",
    "slug-generator",
    "keyword-extractor",
    "canonical-tag-generator",
    "schema-markup-generator",
  ],
  "keyword-extractor": [
    "keyword-density-checker",
    "slug-generator",
    "meta-tag-generator",
    "word-counter",
    "character-counter",
    "keyword-grouping-tool",
  ],
};
